package com.yanbin.dao;

import com.yanbin.model.CompanyKey;
import com.yanbin.model.CompanyKeyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CompanyKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_key
     *
     * @mbggenerated Sun Jul 16 10:55:59 CST 2017
     */
    int countByExample(CompanyKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_key
     *
     * @mbggenerated Sun Jul 16 10:55:59 CST 2017
     */
    int deleteByExample(CompanyKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_key
     *
     * @mbggenerated Sun Jul 16 10:55:59 CST 2017
     */
    int deleteByPrimaryKey(String textKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_key
     *
     * @mbggenerated Sun Jul 16 10:55:59 CST 2017
     */
    int insert(CompanyKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_key
     *
     * @mbggenerated Sun Jul 16 10:55:59 CST 2017
     */
    int insertSelective(CompanyKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_key
     *
     * @mbggenerated Sun Jul 16 10:55:59 CST 2017
     */
    List<CompanyKey> selectByExample(CompanyKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_key
     *
     * @mbggenerated Sun Jul 16 10:55:59 CST 2017
     */
    CompanyKey selectByPrimaryKey(String textKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_key
     *
     * @mbggenerated Sun Jul 16 10:55:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") CompanyKey record, @Param("example") CompanyKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_key
     *
     * @mbggenerated Sun Jul 16 10:55:59 CST 2017
     */
    int updateByExample(@Param("record") CompanyKey record, @Param("example") CompanyKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_key
     *
     * @mbggenerated Sun Jul 16 10:55:59 CST 2017
     */
    int updateByPrimaryKeySelective(CompanyKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_key
     *
     * @mbggenerated Sun Jul 16 10:55:59 CST 2017
     */
    int updateByPrimaryKey(CompanyKey record);
}