package com.yanbin.dao;

import com.yanbin.model.ContentKey;
import com.yanbin.model.ContentKeyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_key
     *
     * @mbggenerated Sun Jul 16 10:55:31 CST 2017
     */
    int countByExample(ContentKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_key
     *
     * @mbggenerated Sun Jul 16 10:55:31 CST 2017
     */
    int deleteByExample(ContentKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_key
     *
     * @mbggenerated Sun Jul 16 10:55:31 CST 2017
     */
    int deleteByPrimaryKey(String textKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_key
     *
     * @mbggenerated Sun Jul 16 10:55:31 CST 2017
     */
    int insert(ContentKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_key
     *
     * @mbggenerated Sun Jul 16 10:55:31 CST 2017
     */
    int insertSelective(ContentKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_key
     *
     * @mbggenerated Sun Jul 16 10:55:31 CST 2017
     */
    List<ContentKey> selectByExample(ContentKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_key
     *
     * @mbggenerated Sun Jul 16 10:55:31 CST 2017
     */
    ContentKey selectByPrimaryKey(String textKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_key
     *
     * @mbggenerated Sun Jul 16 10:55:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") ContentKey record, @Param("example") ContentKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_key
     *
     * @mbggenerated Sun Jul 16 10:55:31 CST 2017
     */
    int updateByExample(@Param("record") ContentKey record, @Param("example") ContentKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_key
     *
     * @mbggenerated Sun Jul 16 10:55:31 CST 2017
     */
    int updateByPrimaryKeySelective(ContentKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_key
     *
     * @mbggenerated Sun Jul 16 10:55:31 CST 2017
     */
    int updateByPrimaryKey(ContentKey record);
}