package com.yanbin.dao;

import com.yanbin.model.Job;
import com.yanbin.model.JobExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Job
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    int countByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Job
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    int deleteByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Job
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    int deleteByPrimaryKey(String url);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Job
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    int insert(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Job
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    int insertSelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Job
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    List<Job> selectByExample(JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Job
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    Job selectByPrimaryKey(String url);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Job
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    int updateByExampleSelective(@Param("record") Job record, @Param("example") JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Job
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    int updateByExample(@Param("record") Job record, @Param("example") JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Job
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    int updateByPrimaryKeySelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Job
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    int updateByPrimaryKey(Job record);
}