package com.yanbin.model;

public class CompanyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_key.text_key
     *
     * @mbggenerated Sun Jul 16 10:55:59 CST 2017
     */
    private String textKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_key.count
     *
     * @mbggenerated Sun Jul 16 10:55:59 CST 2017
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_key.text_key
     *
     * @return the value of company_key.text_key
     *
     * @mbggenerated Sun Jul 16 10:55:59 CST 2017
     */
    public String getTextKey() {
        return textKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_key.text_key
     *
     * @param textKey the value for company_key.text_key
     *
     * @mbggenerated Sun Jul 16 10:55:59 CST 2017
     */
    public void setTextKey(String textKey) {
        this.textKey = textKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_key.count
     *
     * @return the value of company_key.count
     *
     * @mbggenerated Sun Jul 16 10:55:59 CST 2017
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_key.count
     *
     * @param count the value for company_key.count
     *
     * @mbggenerated Sun Jul 16 10:55:59 CST 2017
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}