package com.yanbin.model;

public class Job {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Job.url
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Job.company_name
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Job.title
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Job.advantage
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    private String advantage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Job.city
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Job.type
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Job.salary
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    private String salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Job.experience
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    private String experience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Job.education
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Job.number
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Job.position
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Job.company_size
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    private String companySize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Job.company_type
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    private String companyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Job.company_industry
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    private String companyIndustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Job.company_page
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    private String companyPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Job.company_address
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    private String companyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Job.required
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    private String required;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Job.public_date
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    private String publicDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Job.url
     *
     * @return the value of Job.url
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Job.url
     *
     * @param url the value for Job.url
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Job.company_name
     *
     * @return the value of Job.company_name
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Job.company_name
     *
     * @param companyName the value for Job.company_name
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Job.title
     *
     * @return the value of Job.title
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Job.title
     *
     * @param title the value for Job.title
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Job.advantage
     *
     * @return the value of Job.advantage
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public String getAdvantage() {
        return advantage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Job.advantage
     *
     * @param advantage the value for Job.advantage
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public void setAdvantage(String advantage) {
        this.advantage = advantage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Job.city
     *
     * @return the value of Job.city
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Job.city
     *
     * @param city the value for Job.city
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Job.type
     *
     * @return the value of Job.type
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Job.type
     *
     * @param type the value for Job.type
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Job.salary
     *
     * @return the value of Job.salary
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public String getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Job.salary
     *
     * @param salary the value for Job.salary
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public void setSalary(String salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Job.experience
     *
     * @return the value of Job.experience
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public String getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Job.experience
     *
     * @param experience the value for Job.experience
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public void setExperience(String experience) {
        this.experience = experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Job.education
     *
     * @return the value of Job.education
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Job.education
     *
     * @param education the value for Job.education
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Job.number
     *
     * @return the value of Job.number
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Job.number
     *
     * @param number the value for Job.number
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Job.position
     *
     * @return the value of Job.position
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Job.position
     *
     * @param position the value for Job.position
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Job.company_size
     *
     * @return the value of Job.company_size
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public String getCompanySize() {
        return companySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Job.company_size
     *
     * @param companySize the value for Job.company_size
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public void setCompanySize(String companySize) {
        this.companySize = companySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Job.company_type
     *
     * @return the value of Job.company_type
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public String getCompanyType() {
        return companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Job.company_type
     *
     * @param companyType the value for Job.company_type
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public void setCompanyType(String companyType) {
        this.companyType = companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Job.company_industry
     *
     * @return the value of Job.company_industry
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public String getCompanyIndustry() {
        return companyIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Job.company_industry
     *
     * @param companyIndustry the value for Job.company_industry
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public void setCompanyIndustry(String companyIndustry) {
        this.companyIndustry = companyIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Job.company_page
     *
     * @return the value of Job.company_page
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public String getCompanyPage() {
        return companyPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Job.company_page
     *
     * @param companyPage the value for Job.company_page
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public void setCompanyPage(String companyPage) {
        this.companyPage = companyPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Job.company_address
     *
     * @return the value of Job.company_address
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Job.company_address
     *
     * @param companyAddress the value for Job.company_address
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Job.required
     *
     * @return the value of Job.required
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public String getRequired() {
        return required;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Job.required
     *
     * @param required the value for Job.required
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public void setRequired(String required) {
        this.required = required;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Job.public_date
     *
     * @return the value of Job.public_date
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public String getPublicDate() {
        return publicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Job.public_date
     *
     * @param publicDate the value for Job.public_date
     *
     * @mbggenerated Sun Jul 16 09:39:29 CST 2017
     */
    public void setPublicDate(String publicDate) {
        this.publicDate = publicDate;
    }
}